#!/bin/sh

cat - >/etc/inetd.dpg.conf <<EOF
4501 stream tcp nowait root stdin2file stdin2file /dev/acq400.1.awg
4511 stream tcp nowait root cat cat /dev/acq400.1.awg
4521 stream tcp nowait root stl2raw.load stl2raw.load 1
4531 stream tcp nowait root bb.sha1sum bb.sha1sum 1
#4541 stream tcp nowait root sigdef2raw sigdef2raw /dev/acq400.1.awg
#4551 stream tcp nowait root cat cat /tmp/acq400.1.awg.worktodo
EOF

inetd /etc/inetd.dpg.conf


